---
title: "P8105 Homework6"
author: 'Zanis Fang, UID: ZF2213'
date: "11/16/2018"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

### Problem 1


```{r}
# read data from github repo
homicide <- read_csv("https://raw.githubusercontent.com/washingtonpost/data-homicides/master/homicide-data.csv") %>% 
	# create city_state variable
	unite(col = "city_state", city:state, sep = ", ", remove = FALSE) %>% 
	# create a variable for resolved
	mutate(resolved = disposition %in% "Closed by arrest") %>%
	# select cities with victim race
	filter(!(city_state %in% c("Dallas, TX",
														 "Phoenix, AZ",
														 "Kansas City, MO",
														 "Tulsa, AL"))) %>%
	# change victim to numeric variable, race into factors
	mutate(victim_age = as.numeric(victim_age),
				# victim_race = if_else(victim_race == "White", "White", "Non-White"),
				 victim_race = fct_relevel(victim_race, "White")) 

glm_conf <- function(city_data){
	glm_result <- glm(resolved ~ victim_age + victim_sex + victim_race, data = city_data)
	glm_conf <- confint(glm_result)
	glm_result <- broom::tidy(glm_result)
	cbind(glm_result, glm_conf)
}

glm_baltimore <- homicide %>%
	filter(city_state == "Chicago, IL") #%>% 
	glm(resolved ~ victim_age + victim_sex + victim_race, 
		data = .)
	

glm_all_cities <- homicide %>% 
	select(city_state, resolved, victim_age, victim_sex, victim_race) %>%
	group_by(city_state) %>% 
	nest(resolved, victim_age, victim_sex, victim_race) %>%
	# get logistic regression model
	mutate(glm_model = map(.x = data,
												 .f = ~ glm(resolved ~ victim_age + victim_sex + victim_race, 
												 					 data = .x))) %>% 
	group_by(city_state) %>% 
	# get confidence interval
	mutate(conf = glm_model[[1]] %>% confint() %>% as_tibble %>% list) %>% 
	# tidy the output
	mutate(glm_model = map(.x = glm_model, .f = ~ broom::tidy(.x))) %>%
	select(city_state, glm_model, conf) %>%
	filter(city_state == "Chicago, IL") %>%
	unnest(glm_model, .perserve = conf) %>% View
	rename("conf_low" = "2.5 %", "conf_high" = "97.5 %") %>% 
	filter(term == "victim_raceBlack") %>% 
	select(city_state, estimate, conf_low, conf_high)
	
		
broom::tidy(glm_baltimore) %>%
	filter(term == "victim_raceBlack") %>% confint()
	mutate(conf_low = map2_dbl(.x = estimate,
										 .y = std.error,
										 .f = ~ .x - qnorm(0.975) * .y)) %>% 
	mutate(conf_high = map2_dbl(.x = estimate,
										 .y = std.error,
										 .f = ~ .x + qnorm(0.975) * .y))

exp(1)^confint(glm_baltimore)


```


